package ar.edu.unlu.poo.juegomesa;

//EN ESTE OBJETO ESTARIA DEFINIDA LA CLAVE QUE INSERTA CADA JUGADOR
//PUEDE SER UTILIZADO TANTO PARA SOLUCION COMO RESPUESTA
//ESTARIA FORMADA POR 5 COLORES


public class Clave {
}
