package ar.edu.unlu.poo.juegomesa;

//SE DEFINE EL COMPORTAMIENTO DE CADA JUGADOR.
//VIA UNA VARIABLE "TURNO" SE PODRIA DECIDIR QUIEN ADIVINA Y QUIEN INSERTA LA SOLUCION.
//TENDRIA UNA CLAVE, QUIEN TENGA EL "TURNO" DE DAR PISTAS TIENE LA CLAVE SOLUCION.
//DE LO CONTRARIO SE UTILIZA PARA MOSTRAR U COMPARAR.


public class Jugador {
}
