package ar.edu.unlu.poo.juegomesa;

//MANTIENE HISTORIAL DE RONDAS JUGADAS EN UN TURNO
//JUGADOR QUE PUSO LA CONTRASEÑA
//JUGADOR QUE ADIVINA
//NUMERO INTENTOS
//CLAVE SECRETA


public class Ronda {
}
